name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: ./.github/composite-actions/common

      - name: Generate docs
        id: run-build-docs
        if: steps.changesets.outputs.published == 'true'
        run: pnpm build:docs

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version-packages
          commit: 'ci(changesets): version packages'
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update changelog
        if: steps.changesets.outputs.published == 'true'
        run: |
          git checkout -b changelog/main
          pnpm changelog
          pnpm changelog:commit
          pr_url=$(gh pr create --base main --head bot-branch --title "Update Root Changelog")
          pr_number=$(basename $pr_url)
          gh pr review create $pr_number --approve

      - name: Publish Storybook to Chromatic
        if: steps.changesets.outputs.published == 'true'
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: 'storybook-static'
          workingDir: 'apps/docs'
          zip: true
          exitOnceUploaded: true
